spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_search_api
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true